name: npm

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org/"

      - name: npm ci
        run: npm ci

      - name: npm version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm version minor

      - name: build
        run: npm run build

      - name: publish
        run: npm publish --access public

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write
